### ISSUE TITLE
Please add a Back Button

### ISSUE THREAD

**Issue by BrainZap** [airgap-it/airgap-wallet#10]
In AirGap Wallet (iOS), there's no way to back out of the "Add Coins" screen.   If I decide I don't want to add a coin, the only way back to the main screen is to shut down the app completely and go back in.

**Comment by pascuin** [comment]
Thanks for reporting this issue. Unfortunately we cannot reproduce it, see the screenshots.

Could you please let us know if this is the screen you've encountered this issue? Also it would be great if you could give us some insights which device you're using and which iOS version you're running.

**iOS**
![image](https://user-images.githubusercontent.com/9214127/59486860-166eea00-8e7b-11e9-86a5-2ce5fd1145b8.png)

**Android**
![image](https://user-images.githubusercontent.com/9214127/59486871-1e2e8e80-8e7b-11e9-8341-7a99312c899a.png)

**Comment by BrainZap** [comment]
Only a blind person can't see a "Back" button.  It wasn't there for the last couple of days.  I restarted the app and there it is.
