### ISSUE TITLE
Android 12 incompatible

### ISSUE THREAD

**Issue by khuderm** [airgap-it/airgap-wallet#107]
Upgraded my Pixel 3a XL from Android 11 to 12. Noticed the AirGap wallet app had disappeared but the vault app was still there. Tried to reinstall the app from the play store. It downloads and attempts to install the app but then says the app can't install and to try again. 
![Screenshot_20211023-104321](https://user-images.githubusercontent.com/8462132/138566463-8fdc733d-2738-48d9-a5f2-b897a972222f.png)

**Comment by AndreasGassmann** [comment]
Hi. Sorry for taking so long to reply.

We were aware of this issue, even one of our team members had it. We contacted google, but we nobody seems to know what exactly is going on. The solution google provided us was basically clearing the local cache, removing the application and trying to install it again. This did work for our team member, but is obviously less than ideal. But sadly, we don't have any other solution for this at this time as it seems to be an Android / Play Store issue.
