### ISSUE TITLE
Unable to connect vault with wallet - cannot scan QR code

### ISSUE THREAD

**Issue by fineous** [airgap-it/airgap-wallet#112]
I am unable to connect my airgap wallets to my vault. The vault (the v3.12 apk) is on a separate phone, a Samsung Galaxy S6 (SM-G920F). One wallet (the v 3.13 apk) is on another android phone, a Samsung Galaxy A3 (SM-A310F) and the other (the v 3.10 appimage) is on a laptop running Debian 11. I can see the qr-code from the vault in the photo area of both wallets but the wallets do not detect it.

Update: After adding an account to the vault I was able to import that account into the wallet on the phone. Perhaps a notification should pop up when trying to scan a vault without accounts?

**Comment by shanness** [comment]
I'm having the same problems.  Tried both the 3.10 appimage and 3.10 and 3.13 github source via npm start.  The vault image is clear, but the wallet fails to read it.  Perhaps it's the same prob @fineous mentioned above, but (yet again), I lost my secret on my vault and can't add any coins after re-adding it, so can't test if it's that :(
