### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by ayushkumar63123** [airgap-it/airgap-wallet#113]
I received the below error while testing the code.
Run npm run actions:prettier

> airgap-wallet@0.0.1 actions:prettier /home/runner/work/airgap-wallet/airgap-wallet
> prettier "src/**/*.ts" "src/**/*.js" "e2e/**/*.ts" "angular.json" "README.md" --list-different

src/app/app-routing.module.ts
src/app/app.component.ts
src/app/capacitor-plugins/definitions.ts
src/app/components/account-edit-popover/account-edit-popover.component.ts
src/app/components/tezos-fa-form/tezos-fa-form.component.ts
src/app/components/tezos-fa-form/tezos-fa-form.facade.ts
src/app/components/tezos-fa-form/tezos-fa-form.store.ts
src/app/components/tezos-fa-form/tezos-fa-form.types.ts
src/app/components/tezos-fa-form/tezos-fa-form.utils.ts
src/app/components/transaction-item/transaction-item.component.ts
src/app/extensions/delegation/MoonbeamDelegationExtensions.ts
src/app/pages/account-add/account-add.ts
src/app/pages/beacon-request/beacon-request.page.ts
src/app/pages/portfolio/portfolio.ts
src/app/pages/sub-account-add-generic/sub-account-add-generic.ts
src/app/pages/sub-account-import/sub-account-import.ts
src/app/services/beacon/beacon.service.ts
src/app/services/interaction/interaction.service.ts
src/app/services/push/push.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! airgap-wallet@0.0.1 actions:prettier: `prettier "src/**/*.ts" "src/**/*.js" "e2e/**/*.ts" "angular.json" "README.md" --list-different`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the airgap-wallet@0.0.1 actions:prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-11-25T16_29_05_293Z-debug.log
Error: Process completed with exit code 1.
If this is a bug I found, please reward if possible.

**Comment by AndreasGassmann** [comment]
Hi. The command you executed checks if code is formatted according to the prettier rules. Ideally, the code should be formatted correctly, but even though it is not at the moment, this is not a bug and does not in any way affect the functionality of the code.
