### ISSUE TITLE
WalletConnect - Connection failure, it seems like the connection via walletconnect cannot be established

### ISSUE THREAD

**Issue by skygunner** [airgap-it/airgap-wallet#116]
While trying to conect via walletconnect qr code, the Android app will immediately pop up this error message, though the connection might be successful after 1 or 2 seconds. 
 Tried 1inch polygon and balancer polygon. 

Version" 3.13.0

**Comment by mlaeng** [comment]
Yesterdays update to 3.28.0 has some updates concerning WalletConnect. It should also support v2. There might be issues, but we have to check each time if it's dapp related due to WalletConnect V1 being turned off.
