### ISSUE TITLE
Camera freezing

### ISSUE THREAD

**Issue by kmanx** [airgap-it/airgap-wallet#12]
Hi, I've had an issue using the wallet app on android. The camera freezes and blacks out. Can't scan any codes. The first time works fine, but after that, nope.

**Comment by kmanx** [comment]
Also, just tried (twice) to do a transaction, but it ended with an error saying:
Transaction broadcasting failed: Error: Failed to check for transaction receipt: {}

**Comment by AndreasGassmann** [comment]
Does it work if you force-close the app and try again?

We've never had a report like that so far, so if it's reproducible, could you please tell us your phone model and the OS you are using so we can try to track it down? Thanks!

**Comment by kmanx** [comment]
Phone model: OnePlus 3T (A3003)
OS: Android 9, Havoc OS 2.4 ROM

How to reproduce:
1. Open AirGap Wallet (after killing the app or restarting phone)
2. Switch to 'Scanner' tab.
3. Camera blacked out, and the app freezes (the issue)
4. Tap Home button, then Overview button and open AirGap Wallet again.
5. Switch to 'Accounts' tab, and 'Scanner' tab again. Then the scanner works.

(The same happens with AirGap Vault)
After the first camera activation, the problem doesn't repeat and the camera works.

Tablet model: Galaxy Tab SM-T561
OS: Android 7.1.2, LineageOS (Guava 7)
How to reproduce:
The same steps, except the 4-th step.

(The same happens with AirGap Vault)
After the first camera activation, the problem doesn't repeat and the camera works.

**Comment by AndreasGassmann** [comment]
Hi, we made a lot of improvements over the last year. One very big change is switching from `cordova` to `capacitor`, which also means that some of the native code is now different.

Does this issue still exist in the latest version?

**Comment by AndreasGassmann** [comment]
I'll close this issue due to inactivity. Please let us know if the issue still exists.
