### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by kmanx** [airgap-it/airgap-wallet#13]
Just tried (twice) to do a transaction, but it ended with an error saying:
`Transaction broadcasting failed: Error: Failed to check for transaction receipt: {}`

**Comment by kmanx** [comment]
I checked on etherscan.io and found that the transaction has been broadcasted, but is still pending. In the AirGap Wallet, there is no outgoing transaction. Maybe it will show after it's successful.

**Comment by kmanx** [comment]
> Just tried (twice) to do a transaction, but it ended with an error saying:
> `Transaction broadcasting failed: Error: Failed to check for transaction receipt: {}`

the same happens with the browser extension, it shows the same message, but the transaction goes through.

**Comment by AndreasGassmann** [comment]
Hi, thanks for your report.

If the API returns an error, we display it to the user in a toast. This message looks like it's coming directly from the API. So the transaction was actually broadcast, but there was an error getting the receipt. It may also be an internal error where we can't calculate the transaction hash locally, I'll look into that.

As for the pending transaction, how long it's pending is obviously entirely up to the blockchain and the fees you set. In our app we currently only display transactions that have been included in a block, pending transactions are not shown (this will change soon and you will also be able to see pending transactions).

**Comment by pascuin** [comment]
@kmanx Did you manage to create a transaction without getting the error?

**Comment by kmanx** [comment]
Hi, today I tried again but the same error persists, in both phone app and chrome extension.
In phone app, I had to kill the app, and open it again, cause it froze after it scanned the transaction qr code.

**Comment by AndreasGassmann** [comment]
As mentioned in the other issue, the apps underwent many changes and got a lot more stable in the last year. Does this issue still exist? (BTW, the chrome extension is no longer supported)

**Comment by AndreasGassmann** [comment]
I'll close this issue due to inactivity. Please let us know if the issue still exists.
