### ISSUE TITLE
WalletConnect - Unable to sign

### ISSUE THREAD

**Issue by silver886** [airgap-it/airgap-wallet#133]
There are various errors when invoking JSON-RPC API methods (eth_sendTransaction, eth_sign).

https://example.walletconnect.org/ is the site that can easily reproduce errors.

- eth_sendTransaction
The following screenshot happened after the transaction is signed.
And there was no response when clicked "confirm".
If click "cancel", the website will say "Call Request Rejected".
![photo_2022-01-28 22 40 59](https://user-images.githubusercontent.com/11664880/151569586-61ba479a-8762-4452-ad3c-5fbb2873dfac.jpeg)
Note: The wallet has no balance, perhaps this is the root cause?

- eth_sign
Wallet only shows this black page.
Click "continue" will dismiss the page and cancel will make website says "Call Request Rejected".
![photo_2022-01-28 22 40 58](https://user-images.githubusercontent.com/11664880/151570126-929a003d-7c89-407c-b556-500e41b8b729.jpeg)

Android version: 12
Wallet version: 3.15.0

Edit: app version and Android version

**Comment by AndreasGassmann** [comment]
Hi, thanks for opening this issue.

The missing balance might be the cause for the first issue, even though I didn't verify it myself.

`eth_sign` is not currently supported, but in the latest version of the Vault (`3.14.0`, currently being reviewed by the stores), we added support for it, so we could probably also add WalletConnect support for it.

Recently we added MetaMask support to AirGap Vault. This integration is a lot more stable than the WalletConnect integration, so you should give that one a try.

**Comment by mlaeng** [comment]
@phildental @silver886 todays update 3.28.0 does improve walletconnect and suppports walletconnect V2. There might still be some issues as a lot can happen between dapp and wallet. Feel free to report back.
