### ISSUE TITLE
Transaction QR not compatible

### ISSUE THREAD

**Issue by silver886** [airgap-it/airgap-wallet#134]
While trying https://gnosis-safe.io/app/, it will generate a transaction through WalletConnect.
However, neither QR Code V3 nor V2 can be used to generate QR code for vault.
![photo_2022-01-28 22 40 55](https://user-images.githubusercontent.com/11664880/151572793-e22e91a3-2678-4a8f-837e-663a4f207629.jpeg)

Android version: 12
Wallet version: 3.15.0

**Comment by AndreasGassmann** [comment]
Can you try the same through our new MetaMask integration (after Vault `3.14.0` is released)? I suspect that this is an issue with the conversion from the WalletConnect request to our QR code format, which might not be compatible, eg. if it's an EIP-1559 transaction.

**Comment by mlaeng** [comment]
I will close this as there was no follow up activity here
