### ISSUE TITLE
Airgap Wallet, Transaction Invalid for creating NFT

### ISSUE THREAD

**Issue by XXVNFT** [airgap-it/airgap-wallet#138]
When trying to put my NFT in the market on Rarible, It uploads to IPFS then when it is trying to "Mint" where it send ransaciton to create your NFT. I open my Airgap Wallet to make the transaction valid, but the error pops up and says:

[Transaction_Invalid_Error]:The transacton is invald and the node did nt accept it.

I do not know how to fix it and I want to fix it as soon as possible. 
![Capture](https://user-images.githubusercontent.com/99344467/153227612-d8b3308e-07da-4e3b-a352-13b2a70f7305.PNG)

**Comment by AndreasGassmann** [comment]
In the error popup on the top right, click on "Show Details" and paste the JSON here.

**Comment by XXVNFT** [comment]
> 
----------------------------------------------------------------
[
  {
    "kind": "branch",
    "id": "proto.011-PtHangz2.implicit.empty_implicit_contract",
    "implicit": "tz1fUxJVxt8ntGcKJ2pMB72jarUmzdMYxNMD"
  }
]
---------------------------------------------------------------------------------

**Comment by AndreasGassmann** [comment]
This error means that your account doesn't have a balance, so the simulation of your transaction fails. Put some tez on it and it should work.
