### ISSUE TITLE
Swiping/pressing back on does not go back in some screens

### ISSUE THREAD

**Issue by simonemike95** [airgap-it/airgap-wallet#143]
Swiping back does not return to the previous screen in some instances in the Android app. This is on a Pixel 5 with Android 12 running the latest release APK (downloaded from repo). Pressing back in the top action bar works properly in all these instances.

This happens when in settings, and entering any of the following screens:
- Dapp Settings
- Dapp Permissions
- API Health Check
- About
- Vault and Wallet Interaction Settings
- Advanced QR Settings

**Comment by AndreasGassmann** [comment]
Sorry for not answering earlier, see the latest comment here: https://github.com/airgap-it/airgap-wallet/issues/154

**Comment by mlaeng** [comment]
@simonemike95 This has been resolved in 3.23.0
