### ISSUE TITLE
Multiple addresses for one account

### ISSUE THREAD

**Issue by akhater** [airgap-it/airgap-wallet#149]
Hi - I have in my AirGap vault one account and multiple addresses 

in metamask it shows me the options to import any of these addresses - however in airgap wallet I can only see the primary one 

Can't figure out a way to let them show

thank you

**Comment by AndreasGassmann** [comment]
AirGap Wallet does not currently support showing multiple addresses of a single account. In the Vault you can use the address explorer to see (and verify) them. If you want to use any addresses besides the first one, you will need to use MetaMask for the time being.

There is a manual way how you can get the other accounts into AirGap Wallet. In the Vault, you can add a new ETH account, enable the advanced options, disable "HD" wallet and then change the last "0" in the derivation to the index of the address you want to see in AirGap Wallet. Then sync that account to the Wallet.

**Comment by akhater** [comment]
> AirGap Wallet does not currently support showing multiple addresses of a single account. In the Vault you can use the address explorer to see (and verify) them. If you want to use any addresses besides the first one, you will need to use MetaMask for the time being.
> 
> There is a manual way how you can get the other accounts into AirGap Wallet. In the Vault, you can add a new ETH account, enable the advanced options, disable "HD" wallet and then change the last "0" in the derivation to the index of the address you want to see in AirGap Wallet. Then sync that account to the Wallet.

That works perfectly thank you - may I ask what is the advantage of the "HD wallet" option or what does it do ?

**Comment by AndreasGassmann** [comment]
The HD wallet option only does a partial derivation, meaning that the online wallet can do the last part of the derivation. The advantage is that you can generate new accounts in your hot wallet without having to access the private key.
