### ISSUE TITLE
Assign names to addresses

### ISSUE THREAD

**Issue by akhater** [airgap-it/airgap-wallet#150]
I use different addresses in the wallet for different purposes - is there a way to assign a name or a tag to each ?

**Comment by AndreasGassmann** [comment]
It is currently not possible to assign names to accounts. You can only give a label to the secret they belong to.

We are planning to add a something like a "contact book" feature in the near future, we'll try to add your request into that feature as well.

**Comment by debeldami** [comment]
Contact book now available in the Vault
