### ISSUE TITLE
[Question] what does the lower greyed out price mean?

### ISSUE THREAD

**Issue by vkhobor** [airgap-it/airgap-wallet#152]
![Screenshot_20220309-222848_AirGap Wallet.jpg](https://user-images.githubusercontent.com/47790799/157539360-ae868c48-d7b0-47be-b16e-7f14c665b60f.jpg)

What does the $3.10 mean on my tezos account?

Thank you

**Comment by AndreasGassmann** [comment]
This is the price for 1 XTZ.
