### ISSUE TITLE
is:issue is:open Wallet didn't pass wallet scrutiny's tests.

### ISSUE THREAD

**Issue by ezxpro** [airgap-it/airgap-wallet#156]
I'm interested on this wallet to hold my crypto, but I`m worried about this:

https://walletscrutiny.com/android/it.airgap.vault/

**Comment by ezxpro** [comment]
Any comments on this?

**Comment by AndreasGassmann** [comment]
This repository is for AirGap Wallet, which is not tracked for reproducibility by walletscrutiny because it doesn't hold any private keys.

The reproducibility issue of the Vault is tracked here: https://github.com/airgap-it/airgap-vault/issues/127
