### ISSUE TITLE
Can't sync btc wallet airgap vault on android (3.15.1) with airgap wallet on windows (3.10.0)

### ISSUE THREAD

**Issue by zxcvqwerasdf** [airgap-it/airgap-wallet#157]
ETH works fine. But not BTC(Segwit)
I copy code from clipboard and it says:
"Incompatible code
Could not parse code. Please make sure this is a valid AirGap code."

**Comment by mottech20** [comment]
Also, will there be a Windows release soon too?

**Comment by AndreasGassmann** [comment]
I will close this issue because the reason the btc segwit wallet cannot be paired is because the versions are not compatible.
