### ISSUE TITLE
Unstaking Transaction Issue

### ISSUE THREAD

**Issue by mmfoster74** [airgap-it/airgap-wallet#158]
I have tried to unstake but the the ATOM is still not available in my wallet. Why is it taking over 2 months for this to happen and when will they be available.

**Comment by AndreasGassmann** [comment]
We just verified that unstaking on ATOM is working. It takes 21 days for ATOM to be unstaked. Please make sure you have the latest version of the app.

I will close this issue because it doesn't seem to be a technical problem. For support, please reach out on Discord or Telegram.
