### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by G33kNoob** [airgap-it/airgap-wallet#16]
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\web3-core-requestmanager-62408819\package.json'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\web3-core-requestmanager-62408819\README.md'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\web3-core-requestmanager-62408819\package-lock.json'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\web3-core-7b19a772\src\extend.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\web3-core-7b19a772\src\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular-devkit\schematics-74b8b469\src\workflow\base.d.ts'npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular-devkit\schematics-74b8b469\src\workflow\base.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\css\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\html\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\javascript\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\css\options.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\html\options.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\javascript\options.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\loader\node-main.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-1563a874.system.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\css\tokenizer.js'
npm WARN tar ENOENT: no such file or directory, lstat 'c:\ionic\airgap-wallet-master\node_modules\.staging\cordova-android-42eb2251\bin\templates\project'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-1b8bca4c.system.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\html\tokenizer.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-1fce0be8.system.js'
npm WARN tar ENOENT: no such file or directory, lstat 'c:\ionic\airgap-wallet-master\node_modules\.staging\cordova-android-42eb2251\bin'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-3ea8955c.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\src\javascript\tokenizer.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-4e5c40c0.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-4ey7zsnj.entry.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\js-beautify-64b0d803\js\lib\unpackers\urlencode_unpacker.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-549b16dd.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-7e664492.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-860d8016.js'
npm WARN tar ENOENT: no such file or directory, lstat 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\forms-c3a71c40\esm5\src\directives'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-9725f31b.system.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-aaf72d6b.system.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-c604bd58.system.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\p-f5zck73c.system.entry.js'npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\collection\icon\request.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\animations-50dfe3a2\esm2015\browser\src\render\css_keyframes\css_keyframes_driver.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\animations-50dfe3a2\esm2015\browser\src\render\css_keyframes\css_keyframes_player.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\animations-50dfe3a2\esm2015\browser\src\render\css_keyframes\direct_style_player.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\animations-50dfe3a2\esm2015\browser\src\render\css_keyframes\element_animation_style_handler.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\animations-50dfe3a2\esm2015\browser\src\render\shared.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\esm\legacy\shadow-css-984bac74-549b16dd.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\esm\shadow-css-984bac74-549b16dd.js'npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\cjs\shadow-css-984bac74-b2177096.js'npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\esm\polyfills\system.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\collection\icon\utils.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\collection\icon\validate.js'
npm WARN tar ENOENT: no such file or directory, lstat 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\compiler-cli-4b60e70e\src\ngtsc\metadata\src'
npm WARN tar ENOENT: no such file or directory, lstat 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\compiler-cli-4b60e70e\src\ngtsc\metadata'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\collection\collection-manifest.json'npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\ionicons-edd3b4c2\dist\ionicons\data.json'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\platform-browser-c83c5304\esm5\src\security\dom_sanitization_service.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\http.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\public_api.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\verify\lines.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\verify\lines.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\verify\lintError.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\verify\lintError.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\verify\parse.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\verify\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\formatter\abstractFormatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\formatter\abstractFormatter.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\formatter\formatter.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\formatter\formatter.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\abstractRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\abstractRule.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\optionallyTypedRule.d.ts'npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\optionallyTypedRule.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\rule.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\rule.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\typedRule.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\rule\typedRule.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\blockScopeAwareRuleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\blockScopeAwareRuleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\programAwareRuleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\testing\src\api.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\programAwareRuleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\testing\src\backend.js' npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\ruleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\testing\src\module.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\ruleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\scopeAwareRuleWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\testing\src\request.js' npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\scopeAwareRuleWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\http\testing\testing.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\syntaxWalker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\browserify-400d9850\test\field\node_modules\z-object\browser.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\index.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\browserify-400d9850\test\field\node_modules\z-object\main.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@angular\common-65ef8156\esm5\public_api.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\syntaxWalker.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\browserify-400d9850\test\field\node_modules\z-object\package.json'
npm WARN tar ENOENT: no such file or directory, lstat 'c:\ionic\airgap-wallet-master\node_modules\.staging\browserify-400d9850\test'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\walkContext.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\walkContext.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\walker.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\language\walker\walker.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\arrowReturnShorthand.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\arrowReturnShorthand.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\banTsIgnore.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\banTsIgnore.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\className.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\className.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\curly.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\curly.examples.js' npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\functionConstructor.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\functionConstructor.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noAny.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noAny.examples.js' npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noEmptyInterface.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noEmptyInterface.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noObjectLiteralTypeAssertion.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noObjectLiteralTypeAssertion.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noSparseArrays.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noSparseArrays.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noStringThrowRule.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noStringThrowRule.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noUnnecessaryCallbackWrapper.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noUnnecessaryCallbackWrapper.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\airgap-coin-lib-90db9f4a\src\serializer\validators\validators.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noUseBeforeDeclare.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\noUseBeforeDeclare.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\objectLiteralSortKeys.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\objectLiteralSortKeys.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\oneVariablePerDeclaration.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\oneVariablePerDeclaration.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\onlyArrowFunctions.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\onlyArrowFunctions.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\preferTemplate.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\preferTemplate.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\preferWhile.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\preferWhile.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\radix.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\radix.examples.js' npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\staticThis.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\staticThis.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\switchDefault.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\switchDefault.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\typedef.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@ionic\core-ec1e327a\dist\collection\components\content\content-interface.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\typedef.examples.js'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@ionic\core-ec1e327a\dist\collection\components\content\content.css'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\tslint-605f49bc\lib\rules\code-examples\unnecessaryElse.examples.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'c:\ionic\airgap-wallet-master\node_modules\.staging\@ionic\core-ec1e327a\dist\collection\components\content\content.js'

**Comment by AndreasGassmann** [comment]
Hi.

This looks like an npm issue. Did you simply try to do `npm install` again? Do other npm projects work?

If that doesn't work we need some additional information about your setup, like node and npm version, operating system, etc.

**Comment by AndreasGassmann** [comment]
Because we have not heard back from the author of this issue, I'll close it.
