### ISSUE TITLE
AirGap Connection via WalletConnect cannot be established

### ISSUE THREAD

**Issue by elaine-herrera** [airgap-it/airgap-wallet#165]
The connection cannot be established when using AirGap app version 3.9 on iOS 15.4.1 to connect via WalletConnect [https://example.walletconnect.org](https://example.walletconnect.org) .

**Comment by Nightenom** [comment]
Same issue for LifeBeyond game rewards.
Also trying to scan more than one QR doesn't work, app doesn't show any recognition results

**Comment by mlaeng** [comment]
With today's version 3.28.0 we improved WalletConnect. There might be some issues left or some dapps may cause issues though as WalletConnect did also switch to V2 recently. Let us know if that works for you.
