### ISSUE TITLE
AE transaction stuck at 145 confirmations

### ISSUE THREAD

**Issue by ecshanewiley** [airgap-it/airgap-wallet#170]
Hi. I sent some æternity to an exchange from my Airgap wallet and it showing on the exchange that the transaction is stuck on 145 confirmations. I'm not sure how to fix this. Is there a need to add more fees to this transaction via the airgap wallet? 

Transaction ID: https://explorer.aeternity.io/transactions/th_2eBf1TYNsxnocDyjPrVLoPE3zv4ehNSCpPPZKrNjCX9nbYa2QW

Thanks for your help. 

![Aeternity](https://user-images.githubusercontent.com/85648385/169662272-123b0f30-30da-4125-862f-41d9761a199e.png)
![IMG_9553](https://user-images.githubusercontent.com/85648385/169662509-4e387d41-74fa-4f2a-9edf-8d21800c08c8.PNG)
![IMG_9551](https://user-images.githubusercontent.com/85648385/169662510-bc35c01b-929d-4226-8cbb-59e87c2086a9.PNG)
<img width="1087" alt="Screen Shot 2022-05-21 at 9 59 01 AM" src="https://user-images.githubusercontent.com/85648385/169662527-1f6c5ddc-722b-4427-b52b-ccc227c23221.png">

**Comment by AndreasGassmann** [comment]
Hi, sorry for the late reply.

Once the signed transaction is sent to the aeternity network and included in a block, there is nothing you have to do from your side. Every time a block is mined, the "confirmation" count is increased by one.

If the number of confirmations gets stuck, then there are 2 possible causes:
1. The block explorer is having issues (eg. the node it uses crashed and it's not getting updated)
2. The chain experienced some kind of problem and no new blocks are mined

I'm not sure what the issues was here, but it looks like your transaction now has 5000+ confirmations and your issue should be resolved, I assume.

Let us know if you have any further questions!
