### ISSUE TITLE
Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [airgap-it/airgap-wallet#189]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

**Comment by AndreasGassmann** [comment]
For AirGap Vault, we have a GitHub Actions pipeline to build a linux edition. Our plan is to use a similar pipeline in this repo as well, but we haven't gotten around to doing that.

Feel free to create a PR to add Flatpak to the AirGap Vault application, then it will also be available for AirGap Wallet once we port the script over.

**Comment by x80486** [comment]
I think that's doable. I'm maintaining a couple of these these days, so it would be great if after is done, the `AirGap` teams takes care of the "official maintenance", also due to the nature if the application.

I'll try to spend some time and see if I can get it to completion.

On a different note, I think it's better to publish the Flatpak to Flathub, because that's the main shop for Flatpak applications these days.
