### ISSUE TITLE
EVM transactions wrong direction.

### ISSUE THREAD

**Issue by Originalimoc** [airgap-it/airgap-wallet#195]
Probably caused by mismatched UPPER/lower case of the address in the processed transaction data. Which shouldn't happen as EVM addresses' case is used as the checksum(?)

**Comment by mlaeng** [comment]
Hey, can you please explain what you did exactly and what happened or went wrong? Thank you!

**Comment by mlaeng** [comment]
I will close this as it is unclear what it is about. Feel free to reopen an issue with more context.
