### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Poussinou** [airgap-it/airgap-wallet#2]
Hi,

What is the license of this project? If you haven't already choose, I would suggest GNU GPL v3.

The goal of this question is to know if we should have a look at this app to include it in [F-Droid](https://f-droid.org/), if you're ok with that.

**Comment by Poussinou** [comment]
@AndreasGassmann Any news about this?

**Comment by AndreasGassmann** [comment]
@Poussinou Sorry, no news yet.

We would definitely like to have the app included in F-Droid. I assume you need us to set a license in order to do that?

**Comment by AndreasGassmann** [comment]
I'm happy to tell you that both apps, [AirGap Wallet](https://github.com/airgap-it/airgap-wallet/blob/master/LICENSE.md) and [AirGap Vault](https://github.com/airgap-it/airgap-vault/blob/master/LICENSE.md) are now `MIT` licensed! 🙂 

@Poussinou @ligi @Sword-Smith @GlenCooper
