### ISSUE TITLE
firefox web browsers

### ISSUE THREAD

**Issue by Motophan** [airgap-it/airgap-wallet#202]
your site does not work on firefox desktop

works with chrome

lmk if you have any questions

reproducible steps:
1) load up your website on firefox
2) add a wallet from the vault
3) it wont work

solution -> 
use chrome
follow step 1-3

expected behavior
work

existing behavior
dont

**Comment by mlaeng** [comment]
@Motophan this works for me, also in firefox:

1. open Airgap web wallet in firefox
2. Go to vault and tap on the address you want to sync
3. click on Airgap Wallet to sync with
4. tap on "offline device" which shows a sync qr code
5. in the web wallet, tap "read QR" and allow access to the camera
6. scan the qr code that is displayed in teh vault and the address will appear in the web wallet

For a transaction (eg a send):
1. click on the address you want to send from
2. click send
3. enter amount and target address, then click "create transaction"
4. scan the displayed QR with your vault's scanner and confirm
5. scan the QR code which is displayed on the vault app, with your web wallet and confirm again
