### ISSUE TITLE
sign up staking from youves to beacon

### ISSUE THREAD

**Issue by mtmomnmy** [airgap-it/airgap-wallet#219]
Trying several time to sign a staking from yours to beacon via AirGap but not able..any help?

![IMG_4167](https://user-images.githubusercontent.com/129834645/229720023-05a2cdf5-5459-4909-b084-47fe04caee02.jpg)

**Comment by mtmomnmy** [comment]
YOUVES*

**Comment by mlaeng** [comment]
Hello @mtmomnmy, Mumbai introduced a problem with gas estimations. We published a fixed version of Airgap in the app stores (Version 3.25.2) which fixes the issue. This version will also be added to the releases here on GitHub shortly.
