### ISSUE TITLE
Implement of native WalletConnect

### ISSUE THREAD

**Issue by cryptoida** [airgap-it/airgap-wallet#22]
Hello,
You could implement in AirGap Wallet,  the native WalletConnect?
It would be a great option for this community.
Thanks.

**Comment by cryptoida** [comment]
Please let me know.
Thanks

**Comment by AndreasGassmann** [comment]
Hey, sorry for the late response. I thought I replied to you but it seems I didn't.

We're currently looking into this. I'll let you know once I know more.

**Comment by zsoltsandor** [comment]
I second this, also with support for WalletConnect on Stellar (like Lobstr does).

**Comment by AndreasGassmann** [comment]
WalletConnect support has been added a few months ago in [3.8.0](https://support.airgap.it/CHANGELOG-WALLET#380), I simply forgot to close this issue.
