### ISSUE TITLE
Incorrect balance shown

### ISSUE THREAD

**Issue by theolettuce** [airgap-it/airgap-wallet#227]
I am having a hard time because in my wallet I suddenly see 0 bitcoin.
When checking my Bitcoin address balance on BlockExplorer I see my normal bitcoin balance.

Why does AirGap wallet have this bug?

**Comment by mlaeng** [comment]
Hey! We're really sorry you experience that bug. It was a regression introduced with the latest update. If you are using Android you can downgrade one version with the APK you find unter Release in this repo. 

Unfortunately on iOS you can't downgrade. We will fix this within the next 4 days. 

The bug causes the BTC balance lookup to fail, so it doesn't display the balance and only transactions which were cached on the device.

**Comment by peterwilli** [comment]
What version will that be? I just tried it with 3.25.2 and btc balance is still 0

**Comment by mlaeng** [comment]
@peterwilli I am sorry you experience this. If it's urgent, try [v3.25.0](https://github.com/airgap-it/airgap-wallet/releases/tag/v3.25.0). But we already fixed it and are currently testing the new version. Should be in stores within 2-3 days.

**Comment by peterwilli** [comment]
> @peterwilli I am sorry you experience this. If it's urgent, try [v3.25.0](https://github.com/airgap-it/airgap-wallet/releases/tag/v3.25.0). But we already fixed it and are currently testing the new version. Should be in stores within 2-3 days.

I forgot to get back to you. It was magically working again. I think it was some sort of API issue!

**Comment by mlaeng** [comment]
@peterwilli the issue was fixed in version 3.28.0 which was just released. You'll find in in the app stores or for android here on https://github.com/airgap-it/airgap-wallet/releases/tag/v3.28.0 as well... Thanks for your patience.
