### ISSUE TITLE
Polkadot delegation

### ISSUE THREAD

**Issue by pietje429** [airgap-it/airgap-wallet#228]
Unable to stake additional Polkadot on top of current amount staked. Also, when selecting undelegate 'substrate error account balance is not enough'  is given. Account balance is in fact sufficient. Right now unable to stake additional dot or undelegate dot.

**Comment by mlaeng** [comment]
We are coming up with a fix for that. version is currently in testing.

**Comment by mlaeng** [comment]
@pietje429 The issue has been fixed in version 3.28.0, you'll find it in the app stores on for Android here on github as well: https://github.com/airgap-it/airgap-wallet/releases/tag/v3.28.0
