### ISSUE TITLE
Scanning QR codes is a hustle on both of my phones

### ISSUE THREAD

**Issue by telejoshi** [airgap-it/airgap-wallet#233]
Hello everyone,

I have a phone running Android 7 (older) and a newer Huawei. Sometimes one of my phones refuses to scan the QR code even though the code is very visible. 

I have to go back or even recreate the transaction and suddenly it works right away. I don't think it's my camera because I had the same setting both times.

Does anyone else have this problem?

both are V3.29.0

**Comment by debeldami** [comment]
close issue, because no response from the user.
