### ISSUE TITLE
Cannot connect with WalletConnect using QR Code

### ISSUE THREAD

**Issue by jffaust** [airgap-it/airgap-wallet#235]
Hello,

I am trying to connect my wallet to my profile on the [fxhash.xyz](https://www.fxhash.xyz/) website. When I scan the QR code to connect, nothing happens and I don't know how to troubleshoot it.

![image](https://github.com/airgap-it/airgap-wallet/assets/4367222/9b8be19c-8aaa-4716-8f11-8642053908c2)

I see that the website also provided a button "Copy to Clipboard". Maybe I could try it that way but I'm not sure how to submit the text in the AirGap Wallet app.

I searched across the issues on this repo and I did find a couple related to WalletConnect and from what I saw, the version 3.28 came with better support for WalletConnect (including V2). I have AirGap Wallet version 3.31 installed so not sure why it's not working.

Any help would be appreciated.

**Comment by jffaust** [comment]
As a side note, I am able to connect to the website using my Tezos account, which is also done by scanning a QR code but it's done with the [Beacon protocol](https://www.walletbeacon.io/) instead of WalletConnect.

**Comment by jffaust** [comment]
I also tried connecting to the example connection page at: https://example.walletconnect.org/ . In that case, I'm getting a popup with a "Connection Failure" error (vs nothing happening for fxhash.xyz).
![image](https://github.com/airgap-it/airgap-wallet/assets/4367222/c8271774-6c12-40c2-90a5-0587a6392d6f)

**Comment by mlaeng** [comment]
I tried this on my end and it worked.

1. click connect ETH wallet
2. select walletconnect as connection method
3. scan it with the airgap wallet where you have an ETH account setup
4. if you have more than one eth account, select the one you want to connect to
5. wallet is connected and signature request comes up
6. click to sign (depending on your setup the airgap wallet on your phone should pop up or a qr code should be shown to be signed from the airgap vault)
7. sign the message from the vault
8. sync with wallet by scanning qr code or sending it to the wallet

**Comment by mlaeng** [comment]
I will close this due to inactivity from OP

**Comment by mlaeng** [comment]
closed
