### ISSUE TITLE
Uniswap, WalletConnect - Wallet does not implement EIP-712, eth_signTypedData_v4

### ISSUE THREAD

**Issue by chris-bbq** [airgap-it/airgap-wallet#238]
Trying to swap back an ERC-20 Token to ETH on Uniswap.

Getting this error in JavaScript console in browser (Firefox and Brave):

"signTypedData: wallet does not implement EIP-712, falling back to eth_sign Missing or invalid. request() method: eth_signTypedData_v4"

Steps to reproduce:

URL: https://app.uniswap.org/swap

1. Connect Airgap Wallet using WalletConnect
2. Approve Token
3. Swap Token not possible. Nothing pops up in wallet to confirm and sign the swap. In JavaScript console i get the error above.

**Comment by mlaeng** [comment]
Hey @chris-bbq may I ask which version of the AirGap Wallet you were using?

**Comment by chris-bbq** [comment]
Version 3.31.1

**Comment by debeldami** [comment]
@chris-bbq this should be working fine on iOS now though we still have an issue we have to fix on walletconnect compatibility for Android.
