### ISSUE TITLE
Lost Phrase

### ISSUE THREAD

**Issue by piicasso** [airgap-it/airgap-wallet#26]
Hi, I am using AirGap wallet. I lost my recovery words however I am still signed in to the app therefore I can see my current balance, but cannot do anything with it since it needs AirGap Vault installed as well to do anything with my crypto. Are they lost forever.. can my words be changed ?? Please help !

**Comment by pascuin** [comment]
Hey piicasso, if you don't have AirGap Vault installed and don't have your recovery words anymore, I'm afraid that I have to tell you that we can't do anything. AirGap Wallet is not aware of any private key (secret) and only displays the balance and the secret is stored in AirGap Vault.
