### ISSUE TITLE
Chrome Web store link at https://airgap.it is broken

### ISSUE THREAD

**Issue by itkach** [airgap-it/airgap-wallet#28]
- Go to https://airgap.it/
- Scroll all the way down
- Click "Chrome Web Store" button
- Browser opens https://chrome.google.com/webstore/detail/airgap-wallet-alpha/pnfechdbkbaamagemimebpndagedcmgh 
- Observe google's "404. That's an error" page

**Comment by AndreasGassmann** [comment]
Hi @itkach, thanks for the report. The AirGap Chrome Extension is no longer available on the chrome store and is not being developed further. We'll update the website soon to remove the invalid link.
