### ISSUE TITLE
AE wallet sending address placeholder is confusing

### ISSUE THREAD

**Issue by sammy007** [airgap-it/airgap-wallet#3]
In a Send AE screen I see Send To `0x..`. It's confusing, AE addresses starts with `ak_`. iOS.

**Comment by pascuin** [comment]
Thanks for the feedback, we will change this in the next release.

**Comment by AndreasGassmann** [comment]
This has been added and will be released in the next version. https://github.com/airgap-it/airgap-wallet/commit/f64401aa56e99050668c2826df949015d4328c1e
