### ISSUE TITLE
Blinking connect screen when trying to sync Airgap Wallet with dApp

### ISSUE THREAD

**Issue by sean-magin** [airgap-it/airgap-wallet#30]
Whenever I try to sync my Airgap Wallet on iOS with my dApp (https://ecadlabs.github.io/george-cloney/) I just get a repeating blinking "Connect to Beacon" message and no connection. Is this to be expected for the moment?

**Comment by sean-magin** [comment]
It's happening for me when trying to connect to both mainnet and carthagenet. 

![image](https://user-images.githubusercontent.com/14209806/87663366-d84ba480-c7b7-11ea-85ce-3b2251d45bbc.png)

**Comment by AndreasGassmann** [comment]
Hi, thanks for opening the issue.

I just tried it with the store version and it worked on the first try:

![beacon-george](https://user-images.githubusercontent.com/680814/87665725-a9a5dd80-c767-11ea-860b-295f83da32db.jpeg)

Did you ever successfully pair beacon with your wallet?

Can you go to https://walletbeacon.io and give it a try there?

What you can do is go to the settings in the wallet and under "Beacon Settings" you can "Remove All" open connections. It shouldn't be necessary, but just to be sure force close the app after doing that and try again.

**Comment by sean-magin** [comment]
Hey Andreas! Sorry I had a hectic week/weekend. Yeah I successfully synced with the wallet. That bug happens for me whenever I first scan the QR code, then I leave the scanner on the QR code with removing it. After about 3-5 seconds of leaving the scanner on the QR is when I get the blinking effect. Does this happen for you?

**Comment by AndreasGassmann** [comment]
With the video you sent me I think I know what's going on. If you keep scanning the QR code after a successful connect, it will "blink" the connect loader briefly before it sees that it's already connected to that peer. We'll make that behaviour better in the next version.

**Comment by AndreasGassmann** [comment]
I cannot reproduce this in the latest version, this was probably fixed a while ago.
