### ISSUE TITLE
Account Import Onboarding Slider is buggy

### ISSUE THREAD

**Issue by vikramIde** [airgap-it/airgap-wallet#31]
Hi guys,

So in Nokia  android device, When I click on ```Add Coins``` and select a coin lets say ```Aeternity``` the Account Import Onboarding page loads up with a nice slider.

I am able to see <Back> and <Next> button and a slider at the top.

But if I click on back button and change coin and the Account Import page loads up the slider is gone and the next button does't work.

I thought this was a Vault issue but looks like just a buggy slider.

**Comment by AndreasGassmann** [comment]
Thanks. I think that's actually already tracked in our internal issue board. But I'll leave this open so we don't forget it :)

**Comment by mlaeng** [comment]
@vikramIde this has be fixed at some point in the past. Thanks for having reported it. I will close it now.
