### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/airgap-wallet#38]
We should add a dark mode to our app.

This feature was requested by a user in our telegram group.

**Comment by rmu0** [comment]
Any updates regarding this feature request? Wouldn't mind helping implementing this if none of the developers have time to spare though we'd need an agreed upon colorscheme (wouldn't mind creating that either).

**Comment by AndreasGassmann** [comment]
Hi @rmu0. There has been no progress from our side. If you created a PR we would be happy to merge it.

Regarding the color-scheme, would it be possible to go with the default ionic dark mode colors?

**Comment by rmu0** [comment]
> Hi @rmu0. There has been no progress from our side. If you created a PR we would be happy to merge it.
> 
> Regarding the color-scheme, would it be possible to go with the default ionic dark mode colors?

Will get to it when i can, yes going with the default Ionic dark mode colors is fine.
