### ISSUE TITLE
The "Open Blockexplorer" button for cosmos is wrong

### ISSUE THREAD

**Issue by Delivator** [airgap-it/airgap-wallet#39]
Pressing the `Open Blockexplorer` for cosmos links to `https://www.mintscan.io/cosmos/address/<ADDRESS>` which returns a 404.
`https://www.mintscan.io/cosmos/account/<ADDRESS>` would be the correct link.

Example:
Wrong: https://www.mintscan.io/cosmos/address/cosmos1n3f5lm7xtlrp05z9ud2xk2cnvk2xnzkm0rd04s
Correct: https://www.mintscan.io/cosmos/account/cosmos1n3f5lm7xtlrp05z9ud2xk2cnvk2xnzkm0rd04s

**Comment by AndreasGassmann** [comment]
Hi, sorry for not getting back to you earlier. This has been addressed in a recent release and should work now. Thanks for the report! 👍
