### ISSUE TITLE
Transfer failed

### ISSUE THREAD

**Issue by lzy2920788** [airgap-it/airgap-wallet#4]
Transfer failed, prompt:‘’Transaction broadcasting failed Error:Request failed with status code400‘',How to do?

**Comment by pascuin** [comment]
Please update to the latest Wallet version 1.4.3 through the store or with the following release https://github.com/airgap-it/airgap-wallet/releases/tag/v1.4.3

**Comment by lzy2920788** [comment]
The problem has been solved, thank you!
