### ISSUE TITLE
Linux Mobile Wallet App

### ISSUE THREAD

**Issue by trymeouteh** [airgap-it/airgap-wallet#50]
Please create the wallet app for linux phones to allow linux phone users like LibreM 5, Pinephone, Ubuntu Touch, etc users can use and enjoy AirGap.

Linux Mobile Vault App
https://github.com/airgap-it/airgap-vault/issues/39

**Comment by AndreasGassmann** [comment]
See comment in the vault issue. Once one of the apps is working on Linux Mobile, we can open an issue for the other app.
