### ISSUE TITLE
The amount of crypto shown is too high, can't make transfers

### ISSUE THREAD

**Issue by jpedroguimaraes** [airgap-it/airgap-wallet#57]
The account added to my wallet shows a ridiculously high amount of polkadot, which doesn't correspond to any transaction made nor the transaction history adds up.
Furthermore, I can't transfer the polkadot I know for sure I have. When I try to create a transaction, it says for a brief moment it's processing or preparing it, and then it just shows temporarily a dark rectangle at the bottom of the window. The account information stays the same.

I've tried uninstalling it, removing and re-adding the account and both together, with no results.

is this a known issue? How can I fix it?

**Comment by AndreasGassmann** [comment]
This is a known issue and was fixed in a previous wallet release. Which version do you have installed?

**Comment by jpedroguimaraes** [comment]
3.5.8, I believe. The program also shows me this in the "ABOUT" section:
![image](https://user-images.githubusercontent.com/5737348/109400878-2c6c5900-7943-11eb-8c57-a31bfa53b9fb.png)

**Comment by AndreasGassmann** [comment]
It looks like you are using the desktop application. That one will be updated soon. In the mean time, you can use the mobile version, which already includes a fix for this issue.

**Comment by jpedroguimaraes** [comment]
Thanks!
Is there an ETA on the desktop version update?

**Comment by AndreasGassmann** [comment]
The release should be out within a few days.

**Comment by jpedroguimaraes** [comment]
Thank you!

**Comment by AndreasGassmann** [comment]
The new version has been released. Please let us know if you have any issues with it: https://github.com/airgap-it/airgap-wallet/releases/tag/v3.6.3a
