### ISSUE TITLE
Include a memo in the transaction

### ISSUE THREAD

**Issue by sry9681** [airgap-it/airgap-wallet#64]
I have come to realize that there is no way to include a memo when sending crypto for the coins that support it. I was attempting to send Cosmos to Binance and in order for Binance to receive the transaction it requires a specific phrase in the memo which I am unable to do using AirGap. Am I just missing how to do that and if not, is it something that you believe should be added?

**Comment by AndreasGassmann** [comment]
The memo field will be added in the next release, which we are planning to do this week. Sorry for the inconvenience.

**Comment by AndreasGassmann** [comment]
The memo field was included in [3.7.0](https://github.com/airgap-it/airgap-wallet/releases/tag/v3.7.0).
