### ISSUE TITLE
Polkadot Existential Deposit

### ISSUE THREAD

**Issue by c3pp0** [airgap-it/airgap-wallet#65]
Hi!
I have little more than 1 DOT left in my Airgap Wallet and can't transfer it because of the "existential deposit". I changed some `getTransferableBalance()` calls in of airgap-coin-lib's SubstrateProtocol.ts as a quick fix, but I think it would be nice if you could change `excludeExistentialDeposit` via GUI

**Comment by AndreasGassmann** [comment]
Hi.

Yes, this change is already planned. We hope to be able to release it in the next feature update, which should be ready in a couple of weeks.

**Comment by AndreasGassmann** [comment]
This has been fixed a long time ago.
