### ISSUE TITLE
How to add the nonce to cancel a pending transaction ?

### ISSUE THREAD

**Issue by Didz77** [airgap-it/airgap-wallet#67]
I received some ETH from Hiveon and then I tried to send it to my exchange wallet. On AirGap Wallet when I set up the transaction I selected slow & cheap for the Fee (ETH) without knowing that I had to check the congestion status of the network before to be sure that the gas fee would be enough.

I trusted AirGap Wallet and I am pretty disappointed. It's been more than 24 hours. I have been searching online to know how to solve that and apparently I can cancel the pending transaction by sending to myself 0 ETH with the same nonce used on the pending transaction. The problem I have is that I am not able to find a way to add a nonce on the transaction on AirGap Wallet.

I have been reading that some wallets' interfaces provide an advanced setting where I can set a higher gas fee and change the transaction Nonce. Maybe I don't know to do it on AirGap Wallet app but it seems it's not possible to do it ?

Thank you for you help.

**Comment by Didz77** [comment]
Thank you for your answer via email. Here's your answer copy-pasted for those who encountered the same issue:

_AirGap always selects the last nonce that has been included in a block + 1. So if you now create a new transaction while your old one is still pending, it should have the same nonce as the one you sent previously. To confirm this, you can create your new 0 ETH transaction and give it to the Vault for signing. On the signing screen, you can toggle the "extra details" button, which will show you the nonce. (The nonce in that screen is in hex format. You can convert it to decimal by entering the part after "0x" here: https://www.binaryhexconverter.com/hex-to-decimal-converter)_

**Comment by AndreasGassmann** [comment]
Glad to hear you were able to solve the issue. 👍
