### ISSUE TITLE
Airgap wallet won't make an Aeternity transaction

### ISSUE THREAD

**Issue by markoinno** [airgap-it/airgap-wallet#69]
I have tried ae transaction from airgap wallet to gate.io for several times but it doesn't work. It says transaction pending for some time and at the end there's no transaction. While pending blockexplorer says transaction not found.

**Comment by AndreasGassmann** [comment]
It looks like the node is discarding the transaction for some reason. Could you try to increase the fee and try again?

**Comment by markoinno** [comment]
I tried with highest fees but it didn't work. Finally what did work was changing the ae amount. But now another problem- transaction is pending for a few days now. It's stuck on 89th confirmation out of 1500.

**Comment by AndreasGassmann** [comment]
There are 89 confirmations on the block explorer, but it's not getting any more? That would be very odd. If that really is the case, then you would have to reach out to Aeternity directly. Once the transaction is signed and broadcast to the network, AirGap has no control over what happens anymore.

If you could send us the link to the transaction to hi@airgap.it, we can look into it further.

**Comment by markoinno** [comment]
Ok, transaction link sent.

**Comment by AndreasGassmann** [comment]
Thanks. I received your link. It looks like the transaction now has over 2000 confirmations. Maybe the block explorer simply didn't update. I sent you a link to another block explorer via email.

I'll close this issue now because everything seems as it should be.
