### ISSUE TITLE
Chrome Extension: MEW r._handleAsync is not a function

### ISSUE THREAD

**Issue by pascuin** [airgap-it/airgap-wallet#7]
## Description

The [AirGap Wallet Chrome Extension](https://chrome.google.com/webstore/detail/pnfechdbkbaamagemimebpndagedcmgh/publish-accepted?authuser=0&hl=en-US) cannot interact with MyEtherWallet. MyEtherWallet returns a `Uncaught TypeError: r._handleAsync is not a function`

It looks like the correct Ethereum account was loaded but the balance is `0` and should be `0.00058 ETH`

![image](https://user-images.githubusercontent.com/9214127/56131659-5eab8200-5f88-11e9-9e15-c125c894691e.png)

`{"exception":{"values":[{"type":"TypeError","value":"r._handleAsync is not a function","stacktrace":{"frames":[{"colno":17035,"filename":"https://www.myetherwallet.com/js/vendors.929cf3b9.js","function":"r","in_app":true,"lineno":205},{"colno":334176,"filename":"chrome-extension://pnfechdbkbaamagemimebpndagedcmgh/dist/injection.js","function":"?","in_app":true,"lineno":38}]}}],"mechanism":{"data":{"function":"setTimeout"},"handled":true,"type":"instrument"}},"event_id":"ffe3e6309db741df9e59dd344a3e5987","platform":"javascript","sdk":{"name":"sentry.javascript.browser","packages":[{"name":"npm:@sentry/browser","version":"4.6.6"}],"version":"4.6.6","integrations":["Dedupe","InboundFilters","FunctionToString","ExtraErrorData","TryCatch","Breadcrumbs","GlobalHandlers","LinkedErrors","UserAgent","Vue"]},"environment":"web","release":"5.0.9","request":{"url":"https://www.myetherwallet.com/interface","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"}},"extra":{"arguments":[]},"tags":{"network":"ETH","service":"myetherwallet.com","walletType":"web3_wallet"}}
`

## How to reproduce

1. Install and Setup AirGap Vault, download the [Chrome Extension](https://chrome.google.com/webstore/detail/pnfechdbkbaamagemimebpndagedcmgh/publish-accepted?authuser=0&hl=en-US). 
2. Sync an Ethereum account from AirGap Vault to the AirGap Wallet Chrome Extension, the account is now visible in the Chrome Extension and labeled as active.
3. Go to [MyEtherwallet - Access My Wallet](https://www.myetherwallet.com/access-my-wallet)
4. Select Metamask & accept the terms, click on "Access My Wallet"
5. Error is being thrown, balance is not correct.

**Comment by AndreasGassmann** [comment]
The chrome extension is not available anymore, so I'll close this issue.
