### ISSUE TITLE
Cannot view correct Dai balance

### ISSUE THREAD

**Issue by mochizilla** [airgap-it/airgap-wallet#72]
Cannot view correct Dai balance in AirGap wallet. Dai has been added to the wallet screen as a token but shows 0 balance. Etherscan shows correct Dai amount in the token section of wallet.  I also used the exchange part of AirGap wallet to change a token to some Dai. The amount received in the exchange correctly shows in etherscan but AirGap wallet still says 0 balance. I also checked the Sai balance just in case, which shows 0. All other erc tokens in the same wallet display correctly.

**Comment by mochizilla** [comment]
I also uninstalled and reinstalled AirGap wallet and restored from AirGap vault. This is on iOS 14.5!

**Comment by AndreasGassmann** [comment]
What's the contract you are looking at on Etherscan?

In AirGap, we use the following contract: 0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359 https://github.com/airgap-it/airgap-angular-components/blob/master/packages/core/src/lib/services/protocol/tokens.ts#L114

**Comment by mochizilla** [comment]
0x6B175474E89094C44Da98b954EedeAC495271d0F

I think it’s been moved as of November 2020:
https://github.com/makerdao/developerguides/blob/master/mcd/upgrading-to-multi-collateral-dai/upgrading-to-multi-collateral-dai.md

**Comment by mochizilla** [comment]
Sorry I mean November 2019. The contract in AirGap is the same for Sai and Dai. Is that a mistake? 

On coinmarketcap.com the contract for Dai is the 0x6b17 one. 

All other wallets that I’ve used will show my correct Dai balance so I assume they point to 0x6b17 as well.

I’m not sure if there is a legacy contract issue with AirGap or if the contract listed is a mistake. Either way, thanks for looking into it!

**Comment by AndreasGassmann** [comment]
We also saw that they are using the same address. This is a mistake, we already fixed it internally, it will be included in the next version!

**Comment by mochizilla** [comment]
It’s fixed thank you.
