### ISSUE TITLE
exchange transaction issue

### ISSUE THREAD

**Issue by flipflopflipp** [airgap-it/airgap-wallet#83]
so i wanted to exchange eth to xtz but the exchange transactions are still "waiting" since yesterday furthermore i cannot find my account address on tezblock saying unknown address?? what am i doing wrong?

**Comment by AndreasGassmann** [comment]
Did the transaction you sent to the swap provider actually get included into the blockchain? If it did, could you send me the transaction hash and tell me the provider you used (changelly or changenow), then I can take a look. If you prefer you can send us an email to hi@airgap.it with your details.
