### ISSUE TITLE
Tezos Signed Message format

### ISSUE THREAD

**Issue by sbihel** [airgap-it/airgap-wallet#86]
When requesting a signature for a Tezos Signed Message (a string), the message is displayed in its bytes form, which isn't great for the user's consent.

**Comment by ktorn** [comment]
This issue has also been raised recently here, it affects multiple wallets:

[https://tezos.stackexchange.com/questions/5812/tezos-wallet-displays-hex-bytes-instead-of-human-readable-message](https://tezos.stackexchange.com/questions/5812/tezos-wallet-displays-hex-bytes-instead-of-human-readable-message)

**Comment by debeldami** [comment]
We've worked on this internally, it will be available in a future release soon.
