### ISSUE TITLE
wrong aeternity explorer url for account

### ISSUE THREAD

**Issue by marc0olo** [airgap-it/airgap-wallet#90]
not sure if that changed. but just noticed this when testing AirGap =)

currently pointing to:
- https://mainnet.aeternity.io/account/transactions/ak_...

should point to:
- https://explorer.aeternity.io/account/transactions/ak_... (mainnet)
- https://explorer.testnet.aeternity.io/account/transactions/ak_... (testnet)

**Comment by AndreasGassmann** [comment]
Hi, thanks for opening the issue. We already fixed this and it will be included in 3.8.0, which will be released in a few days.
